[theme]
primaryColor="#000000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
port=8050
headless=true

[browser]
gatherUsageStats=false
serverAddress="bounce-mitigation-ui-service"
