apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-enrollment.fullname" . }}-np
  labels:
  {{- include "user-enrollment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.np.type }}
  selector:
    app: user-enrollment
  {{- include "user-enrollment.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.np.ports | toYaml | nindent 2 -}}