apiVersion: v1
kind: Service
metadata:
  name: {{ include "ihelp-store-rest.fullname" . }}-np
  labels:
  {{- include "ihelp-store-rest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.np.type }}
  selector:
    app: ihelp-store-rest
  {{- include "ihelp-store-rest.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.np.ports | toYaml | nindent 2 -}}