apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: {{ .Values.service_type }}
  selector:
    app: {{ .Values.name }}
  clusterIP: {{ .Values.service_ip }}
  ports:
    - name: streamlit-port
      protocol: TCP
      port: {{ .Values.internal_port_1 }}
      targetPort: {{ .Values.external_port_1 }}
      # nodePort: {{ .Values.node_port }}
