apiVersion: v1
kind: Service
metadata:
  name: ihelp-store-rest-np
spec:
  type: NodePort
  selector:
    app: ihelp-store-rest
  ports:
    - name: "54735"
      protocol: TCP	
      port: 54735
      targetPort: 54735
      nodePort: 30005
