apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-capture.fullname" . }}-capture-service
  labels:
    app: data-capture
  {{- include "data-capture.labels" . | nindent 4 }}
spec:
  type: {{ .Values.captureService.type }}
  selector:
    app: data-capture
  {{- include "data-capture.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.captureService.ports | toYaml | nindent 2 -}}