apiVersion: v1
kind: Service
metadata:
  name: user-enrollment-np
spec:
  type: NodePort
  selector:
    app: user-enrollment
  ports:
    - name: "54735"
      protocol: TCP	
      port: 54735
      targetPort: 54735
      nodePort: 30012
