apiVersion: v1
kind: Service
metadata:
  name: user-enrollment-service
  labels:
    app: user-enrollment
spec:
  ports:
    - name: "54735"
      port: 54735
      targetPort: 54735
  selector:
    app: user-enrollment
