version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart:
      always
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      KEYCLOAK_SERVER: 'http://192.168.1.124:8080/'
      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/AnalyticsICE/:/usr/share/nginx/html   
      - ./certs/:/mnt/    
        
    depends_on:
      - analyticsice
      - keycloak
    restart:
      always
      
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: keycloak
    volumes:
      # - ./configurekeycloak/realm-export-analytics.json:/tmp/realm-export-analytics.json
      - ./configurekeycloak/keycloak/data/:/opt/keycloak/data/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin # TODO: Change this
      PROXY_ADDRESS_FORWARDING: 'true'  #important for reverse proxy   
      KEYCLOAK_IMPORT: /tmp/import-realm.json 
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
    depends_on:
      - analyticsice
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev'
#    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --db postgres --db-url-host postgres --db-username postgres --db-password postgres'
#    entrypoint: '/opt/keycloak/bin/kc.sh start --hostname=keycloak'
    restart:
      always
    
  analyticsice:
    image: informationcatalyst/frondend_analytics_ihelp
    container_name: analyticsice
#    network_mode: "host"        
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 24000M
        reservations:
          cpus: '4'
          memory: 24000M
    ports:
#      - '80:80'
#      - '4200:4200'
      - '3001:3001'
#      - '3306:3306'
      - '5002:5002'
#      - '8080:8080'
      
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
      MYSQL_ROOT_PASSWORD: '1234' # TODO: Change this
      MYSQL_USER: 'root' 
      MYSQL_PASS: '1234' # TODO: Change this
      KEYCLOAK_SERVER: 'http://192.168.1.124:8080/'
      NODE_HOST: '0.0.0.0'
      NODE_PORT: 3001 # do not touch
      PYTHON_HOST: '0.0.0.0'
      PYTHON_PORT: '5002' # do not touch
      REALM_PUBLIC_KEY: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyInkevsB7lzIDC7AMdo4SGMqBxG92VaNSjP8CZOVRUVwrS6EbtCoQ01ehMbgsIv8gjdlHYgi7UQRroXlwhPq/4xY8fU+rvWfU4LeSTZi1zjlvTQz2A/f11S4ByMrtVuZBvBln71It+iEr0bZGJ9pGnX7i8m2hI0hoB6cD2W7FV8pOfJXxam5Vn33HqoHyaxunvgPmLcVBv+KyTaSJVgQ3lvf+7sr5YjXPbPGmFrSQPsy9WNELBaU1VbWPIenvxcyE8ApsG1m7BThrNDg7ZAmNmCGNTK1V8R7vxICMXseHqoIMBs+t6ddUkyEBAQMBRPpVjzzVq7vAtH/5g1VbghOwwIDAQAB'
      MODEL_MANAGER: 192.168.1.124:8080
      
    # depends_on:
    #   - keycloak
      
    volumes:
      - datavolume:/var/lib/mysql
      - imageup:/usr/src/app/scriptsML/imagesup
      - settings:/usr/src/app/scriptsML/settings
       # - keycloak:/opt/keycloak/data/
      - ./dist/AnalyticsICE/:/usr/share/nginx/html
      - ./configurekeycloak/keycloak/data/:/configurekeycloak/keycloak/data

    restart:
      always
      

volumes:
  datavolume:
  imageup:
  settings:
  keycloak:
